version: '3.8'

services:
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo_db
    ports:
      - "27017:27017"

  api_service:
    build: .
    restart: always
    container_name: voting-section-api
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"